changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Fixes
      labels:
        - fix
    - title: 🧪 Magic
      labels:
        - "*"
