name: make_docs
on:
  push:
    branches:
      - main
jobs:
  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: snok/install-poetry@v1
      - run: poetry install --only docs
      - run: poetry run mkdocs gh-deploy --force --clean --verbose
